services:
  posPostgresDb:
    image: postgres:15.3
    restart: always

    container_name: pos-database-postgres

    ports:
      - 5432:5432
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - ./postgres:/var/lib/postgresql/data