services:
  posPostgresDb:
    image: postgres:15.3

    container_name: pos-database-postgres

    ports:
      - 5432:5432
    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos

    volumes:
      - ./postgres:/var/lib/postgresql/data